app:
  port: 9000

postgres:
  host: localhost
  port: 5432
  user: ceit_db
  password: root123
  database: ceit_db

#postgresql://ceit_db:0urXtOt30QgI8d4ov5PFDbS07lvUSHqD@dpg-cq3pp9aju9rs739iep8g-a.singapore-postgres.render.com/ceit_db
# mysql:
# #  host: localhost
# #  port: 3306
# #  user: mysql
# #  password: root123
# #  database: naga
#   host: localhost
#   username: root
#   password: root123
#   database: test


