app:
  port: 9000

postgres:
  host: dpg-cq3pp9aju9rs739iep8g-a
  port: 5432
  user: ceit_db
  password: 0urXtOt30QgI8d4ov5PFDbS07lvUSHqD
  database: ceit_db

  
# mysql:
# #  host: localhost
# #  port: 3306
# #  user: mysql
# #  password: root123
# #  database: naga
#   host: localhost
#   username: root
#   password: root123
#   database: test


